# Generated by Django 3.1 on 2020-09-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('from_zip', models.CharField(blank=True, max_length=100, null=True)),
                ('to_zip', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('square_footage', models.CharField(blank=True, max_length=100, null=True)),
                ('is_elevator', models.BooleanField(default=False)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('hear_about_us', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
